services:
  db:
    build: database/machine
    container_name: db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal_net

  server:
    build: server/machine
    container_name: server
    networks:
      - internal_net
    depends_on:
      - db

  ssh:
    build: ssh/machine
    container_name: ssh
    networks:
      - internal_net

  pivot:
    build: pivot/machine
    container_name: pivot
    ports:
      - "22:22"
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  mariadb_data: