services:
  mysql:
    image: web-machine
    hostname: web-machine
    build: database/machine
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal_net
  server:
    image: web-machine
    hostname: web-machine
    build: server/machine
    volumes:
      - ./flag:/flag
    ports:
      - 8000:8000
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

  
volumes:
  mysql_data:
